//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_cargo
    {
        public int Empcar_id { get; set; }
        public Nullable<int> Emp_Id { get; set; }
        public Nullable<int> Car_Id { get; set; }
        public Nullable<int> PC_Id { get; set; }
    
        public virtual cargos cargos { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual planillascontratos planillascontratos { get; set; }
    }
}
