//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public int Pag_Id { get; set; }
        public int TFor_Id { get; set; }
        public string Pag_Num { get; set; }
        public string Pag_Correo { get; set; }
        public string Pag_Motivo { get; set; }
        public Nullable<int> BTC_Id { get; set; }
        public string Per_Rut { get; set; }
    
        public virtual bancostiposcuentas bancostiposcuentas { get; set; }
        public virtual tipoformaspago tipoformaspago { get; set; }
    }
}
